/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabinetsRouteImport } from './routes/cabinets'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppComptabiliteRouteImport } from './routes/_authenticated/app.comptabilite'
import { Route as AuthenticatedAppComptabiliteIndexRouteImport } from './routes/_authenticated/app.comptabilite.index'
import { Route as AuthenticatedAppComptabilitePlanRouteImport } from './routes/_authenticated/app.comptabilite.plan'
import { Route as AuthenticatedAppComptabiliteJournauxRouteImport } from './routes/_authenticated/app.comptabilite.journaux'
import { Route as AuthenticatedAppComptabiliteEcrituresIndexRouteImport } from './routes/_authenticated/app.comptabilite.ecritures.index'
import { Route as AuthenticatedAppComptabiliteEcrituresNouvelleRouteImport } from './routes/_authenticated/app.comptabilite.ecritures.nouvelle'
import { Route as AuthenticatedAppComptabiliteEcrituresIdRouteImport } from './routes/_authenticated/app.comptabilite.ecritures.$id'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetsRoute = CabinetsRouteImport.update({
  id: '/cabinets',
  path: '/cabinets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComptabiliteRoute =
  AuthenticatedAppComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComptabiliteIndexRoute =
  AuthenticatedAppComptabiliteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabilitePlanRoute =
  AuthenticatedAppComptabilitePlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteJournauxRoute =
  AuthenticatedAppComptabiliteJournauxRouteImport.update({
    id: '/journaux',
    path: '/journaux',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteEcrituresIndexRoute =
  AuthenticatedAppComptabiliteEcrituresIndexRouteImport.update({
    id: '/ecritures/',
    path: '/ecritures/',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteEcrituresNouvelleRoute =
  AuthenticatedAppComptabiliteEcrituresNouvelleRouteImport.update({
    id: '/ecritures/nouvelle',
    path: '/ecritures/nouvelle',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteEcrituresIdRoute =
  AuthenticatedAppComptabiliteEcrituresIdRouteImport.update({
    id: '/ecritures/$id',
    path: '/ecritures/$id',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinets': typeof CabinetsRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/comptabilite': typeof AuthenticatedAppComptabiliteRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/comptabilite/journaux': typeof AuthenticatedAppComptabiliteJournauxRoute
  '/app/comptabilite/plan': typeof AuthenticatedAppComptabilitePlanRoute
  '/app/comptabilite/': typeof AuthenticatedAppComptabiliteIndexRoute
  '/app/comptabilite/ecritures/$id': typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  '/app/comptabilite/ecritures/nouvelle': typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  '/app/comptabilite/ecritures/': typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinets': typeof CabinetsRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/comptabilite/journaux': typeof AuthenticatedAppComptabiliteJournauxRoute
  '/app/comptabilite/plan': typeof AuthenticatedAppComptabilitePlanRoute
  '/app/comptabilite': typeof AuthenticatedAppComptabiliteIndexRoute
  '/app/comptabilite/ecritures/$id': typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  '/app/comptabilite/ecritures/nouvelle': typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  '/app/comptabilite/ecritures': typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cabinets': typeof CabinetsRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/comptabilite': typeof AuthenticatedAppComptabiliteRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/comptabilite/journaux': typeof AuthenticatedAppComptabiliteJournauxRoute
  '/_authenticated/app/comptabilite/plan': typeof AuthenticatedAppComptabilitePlanRoute
  '/_authenticated/app/comptabilite/': typeof AuthenticatedAppComptabiliteIndexRoute
  '/_authenticated/app/comptabilite/ecritures/$id': typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  '/_authenticated/app/comptabilite/ecritures/nouvelle': typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  '/_authenticated/app/comptabilite/ecritures/': typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinets'
    | '/contact'
    | '/fonctionnalites'
    | '/legal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/app'
    | '/onboarding'
    | '/app/comptabilite'
    | '/app/'
    | '/app/comptabilite/journaux'
    | '/app/comptabilite/plan'
    | '/app/comptabilite/'
    | '/app/comptabilite/ecritures/$id'
    | '/app/comptabilite/ecritures/nouvelle'
    | '/app/comptabilite/ecritures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinets'
    | '/contact'
    | '/fonctionnalites'
    | '/legal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/onboarding'
    | '/app'
    | '/app/comptabilite/journaux'
    | '/app/comptabilite/plan'
    | '/app/comptabilite'
    | '/app/comptabilite/ecritures/$id'
    | '/app/comptabilite/ecritures/nouvelle'
    | '/app/comptabilite/ecritures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cabinets'
    | '/contact'
    | '/fonctionnalites'
    | '/legal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/comptabilite'
    | '/_authenticated/app/'
    | '/_authenticated/app/comptabilite/journaux'
    | '/_authenticated/app/comptabilite/plan'
    | '/_authenticated/app/comptabilite/'
    | '/_authenticated/app/comptabilite/ecritures/$id'
    | '/_authenticated/app/comptabilite/ecritures/nouvelle'
    | '/_authenticated/app/comptabilite/ecritures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CabinetsRoute: typeof CabinetsRoute
  ContactRoute: typeof ContactRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinets': {
      id: '/cabinets'
      path: '/cabinets'
      fullPath: '/cabinets'
      preLoaderRoute: typeof CabinetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comptabilite': {
      id: '/_authenticated/app/comptabilite'
      path: '/comptabilite'
      fullPath: '/app/comptabilite'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comptabilite/': {
      id: '/_authenticated/app/comptabilite/'
      path: '/'
      fullPath: '/app/comptabilite/'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteIndexRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/plan': {
      id: '/_authenticated/app/comptabilite/plan'
      path: '/plan'
      fullPath: '/app/comptabilite/plan'
      preLoaderRoute: typeof AuthenticatedAppComptabilitePlanRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/journaux': {
      id: '/_authenticated/app/comptabilite/journaux'
      path: '/journaux'
      fullPath: '/app/comptabilite/journaux'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteJournauxRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/ecritures/': {
      id: '/_authenticated/app/comptabilite/ecritures/'
      path: '/ecritures'
      fullPath: '/app/comptabilite/ecritures/'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteEcrituresIndexRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/ecritures/nouvelle': {
      id: '/_authenticated/app/comptabilite/ecritures/nouvelle'
      path: '/ecritures/nouvelle'
      fullPath: '/app/comptabilite/ecritures/nouvelle'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteEcrituresNouvelleRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/ecritures/$id': {
      id: '/_authenticated/app/comptabilite/ecritures/$id'
      path: '/ecritures/$id'
      fullPath: '/app/comptabilite/ecritures/$id'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteEcrituresIdRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
  }
}

interface AuthenticatedAppComptabiliteRouteChildren {
  AuthenticatedAppComptabiliteJournauxRoute: typeof AuthenticatedAppComptabiliteJournauxRoute
  AuthenticatedAppComptabilitePlanRoute: typeof AuthenticatedAppComptabilitePlanRoute
  AuthenticatedAppComptabiliteIndexRoute: typeof AuthenticatedAppComptabiliteIndexRoute
  AuthenticatedAppComptabiliteEcrituresIdRoute: typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  AuthenticatedAppComptabiliteEcrituresNouvelleRoute: typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  AuthenticatedAppComptabiliteEcrituresIndexRoute: typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}

const AuthenticatedAppComptabiliteRouteChildren: AuthenticatedAppComptabiliteRouteChildren =
  {
    AuthenticatedAppComptabiliteJournauxRoute:
      AuthenticatedAppComptabiliteJournauxRoute,
    AuthenticatedAppComptabilitePlanRoute:
      AuthenticatedAppComptabilitePlanRoute,
    AuthenticatedAppComptabiliteIndexRoute:
      AuthenticatedAppComptabiliteIndexRoute,
    AuthenticatedAppComptabiliteEcrituresIdRoute:
      AuthenticatedAppComptabiliteEcrituresIdRoute,
    AuthenticatedAppComptabiliteEcrituresNouvelleRoute:
      AuthenticatedAppComptabiliteEcrituresNouvelleRoute,
    AuthenticatedAppComptabiliteEcrituresIndexRoute:
      AuthenticatedAppComptabiliteEcrituresIndexRoute,
  }

const AuthenticatedAppComptabiliteRouteWithChildren =
  AuthenticatedAppComptabiliteRoute._addFileChildren(
    AuthenticatedAppComptabiliteRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppComptabiliteRoute: typeof AuthenticatedAppComptabiliteRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppComptabiliteRoute:
    AuthenticatedAppComptabiliteRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CabinetsRoute: CabinetsRoute,
  ContactRoute: ContactRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
