/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabinetsRouteImport } from './routes/cabinets'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTiersRouteImport } from './routes/_authenticated/app.tiers'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppFiscaliteRouteImport } from './routes/_authenticated/app.fiscalite'
import { Route as AuthenticatedAppExportRouteImport } from './routes/_authenticated/app.export'
import { Route as AuthenticatedAppComptabiliteRouteImport } from './routes/_authenticated/app.comptabilite'
import { Route as AuthenticatedAppVentesIndexRouteImport } from './routes/_authenticated/app.ventes.index'
import { Route as AuthenticatedAppTresorerieIndexRouteImport } from './routes/_authenticated/app.tresorerie.index'
import { Route as AuthenticatedAppComptabiliteIndexRouteImport } from './routes/_authenticated/app.comptabilite.index'
import { Route as AuthenticatedAppAchatsIndexRouteImport } from './routes/_authenticated/app.achats.index'
import { Route as AuthenticatedAppVentesNouvelleRouteImport } from './routes/_authenticated/app.ventes.nouvelle'
import { Route as AuthenticatedAppVentesIdRouteImport } from './routes/_authenticated/app.ventes.$id'
import { Route as AuthenticatedAppTresorerieIdRouteImport } from './routes/_authenticated/app.tresorerie.$id'
import { Route as AuthenticatedAppComptabilitePlanRouteImport } from './routes/_authenticated/app.comptabilite.plan'
import { Route as AuthenticatedAppComptabilitePeriodesRouteImport } from './routes/_authenticated/app.comptabilite.periodes'
import { Route as AuthenticatedAppComptabiliteJournauxRouteImport } from './routes/_authenticated/app.comptabilite.journaux'
import { Route as AuthenticatedAppComptabiliteJournalRouteImport } from './routes/_authenticated/app.comptabilite.journal'
import { Route as AuthenticatedAppComptabiliteGrandLivreRouteImport } from './routes/_authenticated/app.comptabilite.grand-livre'
import { Route as AuthenticatedAppComptabiliteBalanceAuxiliaireRouteImport } from './routes/_authenticated/app.comptabilite.balance-auxiliaire'
import { Route as AuthenticatedAppComptabiliteBalanceRouteImport } from './routes/_authenticated/app.comptabilite.balance'
import { Route as AuthenticatedAppAchatsNouvelleRouteImport } from './routes/_authenticated/app.achats.nouvelle'
import { Route as AuthenticatedAppAchatsIdRouteImport } from './routes/_authenticated/app.achats.$id'
import { Route as AuthenticatedAppComptabiliteEcrituresIndexRouteImport } from './routes/_authenticated/app.comptabilite.ecritures.index'
import { Route as AuthenticatedAppComptabiliteEcrituresNouvelleRouteImport } from './routes/_authenticated/app.comptabilite.ecritures.nouvelle'
import { Route as AuthenticatedAppComptabiliteEcrituresIdRouteImport } from './routes/_authenticated/app.comptabilite.ecritures.$id'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetsRoute = CabinetsRouteImport.update({
  id: '/cabinets',
  path: '/cabinets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTiersRoute = AuthenticatedAppTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFiscaliteRoute =
  AuthenticatedAppFiscaliteRouteImport.update({
    id: '/fiscalite',
    path: '/fiscalite',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExportRoute = AuthenticatedAppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppComptabiliteRoute =
  AuthenticatedAppComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVentesIndexRoute =
  AuthenticatedAppVentesIndexRouteImport.update({
    id: '/ventes/',
    path: '/ventes/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTresorerieIndexRoute =
  AuthenticatedAppTresorerieIndexRouteImport.update({
    id: '/tresorerie/',
    path: '/tresorerie/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComptabiliteIndexRoute =
  AuthenticatedAppComptabiliteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppAchatsIndexRoute =
  AuthenticatedAppAchatsIndexRouteImport.update({
    id: '/achats/',
    path: '/achats/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVentesNouvelleRoute =
  AuthenticatedAppVentesNouvelleRouteImport.update({
    id: '/ventes/nouvelle',
    path: '/ventes/nouvelle',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVentesIdRoute =
  AuthenticatedAppVentesIdRouteImport.update({
    id: '/ventes/$id',
    path: '/ventes/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTresorerieIdRoute =
  AuthenticatedAppTresorerieIdRouteImport.update({
    id: '/tresorerie/$id',
    path: '/tresorerie/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComptabilitePlanRoute =
  AuthenticatedAppComptabilitePlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabilitePeriodesRoute =
  AuthenticatedAppComptabilitePeriodesRouteImport.update({
    id: '/periodes',
    path: '/periodes',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteJournauxRoute =
  AuthenticatedAppComptabiliteJournauxRouteImport.update({
    id: '/journaux',
    path: '/journaux',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteJournalRoute =
  AuthenticatedAppComptabiliteJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteGrandLivreRoute =
  AuthenticatedAppComptabiliteGrandLivreRouteImport.update({
    id: '/grand-livre',
    path: '/grand-livre',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteBalanceAuxiliaireRoute =
  AuthenticatedAppComptabiliteBalanceAuxiliaireRouteImport.update({
    id: '/balance-auxiliaire',
    path: '/balance-auxiliaire',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteBalanceRoute =
  AuthenticatedAppComptabiliteBalanceRouteImport.update({
    id: '/balance',
    path: '/balance',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppAchatsNouvelleRoute =
  AuthenticatedAppAchatsNouvelleRouteImport.update({
    id: '/achats/nouvelle',
    path: '/achats/nouvelle',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAchatsIdRoute =
  AuthenticatedAppAchatsIdRouteImport.update({
    id: '/achats/$id',
    path: '/achats/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComptabiliteEcrituresIndexRoute =
  AuthenticatedAppComptabiliteEcrituresIndexRouteImport.update({
    id: '/ecritures/',
    path: '/ecritures/',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteEcrituresNouvelleRoute =
  AuthenticatedAppComptabiliteEcrituresNouvelleRouteImport.update({
    id: '/ecritures/nouvelle',
    path: '/ecritures/nouvelle',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)
const AuthenticatedAppComptabiliteEcrituresIdRoute =
  AuthenticatedAppComptabiliteEcrituresIdRouteImport.update({
    id: '/ecritures/$id',
    path: '/ecritures/$id',
    getParentRoute: () => AuthenticatedAppComptabiliteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinets': typeof CabinetsRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/comptabilite': typeof AuthenticatedAppComptabiliteRouteWithChildren
  '/app/export': typeof AuthenticatedAppExportRoute
  '/app/fiscalite': typeof AuthenticatedAppFiscaliteRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/tiers': typeof AuthenticatedAppTiersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/achats/$id': typeof AuthenticatedAppAchatsIdRoute
  '/app/achats/nouvelle': typeof AuthenticatedAppAchatsNouvelleRoute
  '/app/comptabilite/balance': typeof AuthenticatedAppComptabiliteBalanceRoute
  '/app/comptabilite/balance-auxiliaire': typeof AuthenticatedAppComptabiliteBalanceAuxiliaireRoute
  '/app/comptabilite/grand-livre': typeof AuthenticatedAppComptabiliteGrandLivreRoute
  '/app/comptabilite/journal': typeof AuthenticatedAppComptabiliteJournalRoute
  '/app/comptabilite/journaux': typeof AuthenticatedAppComptabiliteJournauxRoute
  '/app/comptabilite/periodes': typeof AuthenticatedAppComptabilitePeriodesRoute
  '/app/comptabilite/plan': typeof AuthenticatedAppComptabilitePlanRoute
  '/app/tresorerie/$id': typeof AuthenticatedAppTresorerieIdRoute
  '/app/ventes/$id': typeof AuthenticatedAppVentesIdRoute
  '/app/ventes/nouvelle': typeof AuthenticatedAppVentesNouvelleRoute
  '/app/achats/': typeof AuthenticatedAppAchatsIndexRoute
  '/app/comptabilite/': typeof AuthenticatedAppComptabiliteIndexRoute
  '/app/tresorerie/': typeof AuthenticatedAppTresorerieIndexRoute
  '/app/ventes/': typeof AuthenticatedAppVentesIndexRoute
  '/app/comptabilite/ecritures/$id': typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  '/app/comptabilite/ecritures/nouvelle': typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  '/app/comptabilite/ecritures/': typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinets': typeof CabinetsRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/export': typeof AuthenticatedAppExportRoute
  '/app/fiscalite': typeof AuthenticatedAppFiscaliteRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/tiers': typeof AuthenticatedAppTiersRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/achats/$id': typeof AuthenticatedAppAchatsIdRoute
  '/app/achats/nouvelle': typeof AuthenticatedAppAchatsNouvelleRoute
  '/app/comptabilite/balance': typeof AuthenticatedAppComptabiliteBalanceRoute
  '/app/comptabilite/balance-auxiliaire': typeof AuthenticatedAppComptabiliteBalanceAuxiliaireRoute
  '/app/comptabilite/grand-livre': typeof AuthenticatedAppComptabiliteGrandLivreRoute
  '/app/comptabilite/journal': typeof AuthenticatedAppComptabiliteJournalRoute
  '/app/comptabilite/journaux': typeof AuthenticatedAppComptabiliteJournauxRoute
  '/app/comptabilite/periodes': typeof AuthenticatedAppComptabilitePeriodesRoute
  '/app/comptabilite/plan': typeof AuthenticatedAppComptabilitePlanRoute
  '/app/tresorerie/$id': typeof AuthenticatedAppTresorerieIdRoute
  '/app/ventes/$id': typeof AuthenticatedAppVentesIdRoute
  '/app/ventes/nouvelle': typeof AuthenticatedAppVentesNouvelleRoute
  '/app/achats': typeof AuthenticatedAppAchatsIndexRoute
  '/app/comptabilite': typeof AuthenticatedAppComptabiliteIndexRoute
  '/app/tresorerie': typeof AuthenticatedAppTresorerieIndexRoute
  '/app/ventes': typeof AuthenticatedAppVentesIndexRoute
  '/app/comptabilite/ecritures/$id': typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  '/app/comptabilite/ecritures/nouvelle': typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  '/app/comptabilite/ecritures': typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cabinets': typeof CabinetsRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/comptabilite': typeof AuthenticatedAppComptabiliteRouteWithChildren
  '/_authenticated/app/export': typeof AuthenticatedAppExportRoute
  '/_authenticated/app/fiscalite': typeof AuthenticatedAppFiscaliteRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/app/tiers': typeof AuthenticatedAppTiersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/achats/$id': typeof AuthenticatedAppAchatsIdRoute
  '/_authenticated/app/achats/nouvelle': typeof AuthenticatedAppAchatsNouvelleRoute
  '/_authenticated/app/comptabilite/balance': typeof AuthenticatedAppComptabiliteBalanceRoute
  '/_authenticated/app/comptabilite/balance-auxiliaire': typeof AuthenticatedAppComptabiliteBalanceAuxiliaireRoute
  '/_authenticated/app/comptabilite/grand-livre': typeof AuthenticatedAppComptabiliteGrandLivreRoute
  '/_authenticated/app/comptabilite/journal': typeof AuthenticatedAppComptabiliteJournalRoute
  '/_authenticated/app/comptabilite/journaux': typeof AuthenticatedAppComptabiliteJournauxRoute
  '/_authenticated/app/comptabilite/periodes': typeof AuthenticatedAppComptabilitePeriodesRoute
  '/_authenticated/app/comptabilite/plan': typeof AuthenticatedAppComptabilitePlanRoute
  '/_authenticated/app/tresorerie/$id': typeof AuthenticatedAppTresorerieIdRoute
  '/_authenticated/app/ventes/$id': typeof AuthenticatedAppVentesIdRoute
  '/_authenticated/app/ventes/nouvelle': typeof AuthenticatedAppVentesNouvelleRoute
  '/_authenticated/app/achats/': typeof AuthenticatedAppAchatsIndexRoute
  '/_authenticated/app/comptabilite/': typeof AuthenticatedAppComptabiliteIndexRoute
  '/_authenticated/app/tresorerie/': typeof AuthenticatedAppTresorerieIndexRoute
  '/_authenticated/app/ventes/': typeof AuthenticatedAppVentesIndexRoute
  '/_authenticated/app/comptabilite/ecritures/$id': typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  '/_authenticated/app/comptabilite/ecritures/nouvelle': typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  '/_authenticated/app/comptabilite/ecritures/': typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinets'
    | '/contact'
    | '/fonctionnalites'
    | '/legal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/app'
    | '/onboarding'
    | '/app/comptabilite'
    | '/app/export'
    | '/app/fiscalite'
    | '/app/support'
    | '/app/tiers'
    | '/app/'
    | '/app/achats/$id'
    | '/app/achats/nouvelle'
    | '/app/comptabilite/balance'
    | '/app/comptabilite/balance-auxiliaire'
    | '/app/comptabilite/grand-livre'
    | '/app/comptabilite/journal'
    | '/app/comptabilite/journaux'
    | '/app/comptabilite/periodes'
    | '/app/comptabilite/plan'
    | '/app/tresorerie/$id'
    | '/app/ventes/$id'
    | '/app/ventes/nouvelle'
    | '/app/achats/'
    | '/app/comptabilite/'
    | '/app/tresorerie/'
    | '/app/ventes/'
    | '/app/comptabilite/ecritures/$id'
    | '/app/comptabilite/ecritures/nouvelle'
    | '/app/comptabilite/ecritures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinets'
    | '/contact'
    | '/fonctionnalites'
    | '/legal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/onboarding'
    | '/app/export'
    | '/app/fiscalite'
    | '/app/support'
    | '/app/tiers'
    | '/app'
    | '/app/achats/$id'
    | '/app/achats/nouvelle'
    | '/app/comptabilite/balance'
    | '/app/comptabilite/balance-auxiliaire'
    | '/app/comptabilite/grand-livre'
    | '/app/comptabilite/journal'
    | '/app/comptabilite/journaux'
    | '/app/comptabilite/periodes'
    | '/app/comptabilite/plan'
    | '/app/tresorerie/$id'
    | '/app/ventes/$id'
    | '/app/ventes/nouvelle'
    | '/app/achats'
    | '/app/comptabilite'
    | '/app/tresorerie'
    | '/app/ventes'
    | '/app/comptabilite/ecritures/$id'
    | '/app/comptabilite/ecritures/nouvelle'
    | '/app/comptabilite/ecritures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cabinets'
    | '/contact'
    | '/fonctionnalites'
    | '/legal'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/comptabilite'
    | '/_authenticated/app/export'
    | '/_authenticated/app/fiscalite'
    | '/_authenticated/app/support'
    | '/_authenticated/app/tiers'
    | '/_authenticated/app/'
    | '/_authenticated/app/achats/$id'
    | '/_authenticated/app/achats/nouvelle'
    | '/_authenticated/app/comptabilite/balance'
    | '/_authenticated/app/comptabilite/balance-auxiliaire'
    | '/_authenticated/app/comptabilite/grand-livre'
    | '/_authenticated/app/comptabilite/journal'
    | '/_authenticated/app/comptabilite/journaux'
    | '/_authenticated/app/comptabilite/periodes'
    | '/_authenticated/app/comptabilite/plan'
    | '/_authenticated/app/tresorerie/$id'
    | '/_authenticated/app/ventes/$id'
    | '/_authenticated/app/ventes/nouvelle'
    | '/_authenticated/app/achats/'
    | '/_authenticated/app/comptabilite/'
    | '/_authenticated/app/tresorerie/'
    | '/_authenticated/app/ventes/'
    | '/_authenticated/app/comptabilite/ecritures/$id'
    | '/_authenticated/app/comptabilite/ecritures/nouvelle'
    | '/_authenticated/app/comptabilite/ecritures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CabinetsRoute: typeof CabinetsRoute
  ContactRoute: typeof ContactRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinets': {
      id: '/cabinets'
      path: '/cabinets'
      fullPath: '/cabinets'
      preLoaderRoute: typeof CabinetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tiers': {
      id: '/_authenticated/app/tiers'
      path: '/tiers'
      fullPath: '/app/tiers'
      preLoaderRoute: typeof AuthenticatedAppTiersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/fiscalite': {
      id: '/_authenticated/app/fiscalite'
      path: '/fiscalite'
      fullPath: '/app/fiscalite'
      preLoaderRoute: typeof AuthenticatedAppFiscaliteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/export': {
      id: '/_authenticated/app/export'
      path: '/export'
      fullPath: '/app/export'
      preLoaderRoute: typeof AuthenticatedAppExportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comptabilite': {
      id: '/_authenticated/app/comptabilite'
      path: '/comptabilite'
      fullPath: '/app/comptabilite'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ventes/': {
      id: '/_authenticated/app/ventes/'
      path: '/ventes'
      fullPath: '/app/ventes/'
      preLoaderRoute: typeof AuthenticatedAppVentesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tresorerie/': {
      id: '/_authenticated/app/tresorerie/'
      path: '/tresorerie'
      fullPath: '/app/tresorerie/'
      preLoaderRoute: typeof AuthenticatedAppTresorerieIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comptabilite/': {
      id: '/_authenticated/app/comptabilite/'
      path: '/'
      fullPath: '/app/comptabilite/'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteIndexRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/achats/': {
      id: '/_authenticated/app/achats/'
      path: '/achats'
      fullPath: '/app/achats/'
      preLoaderRoute: typeof AuthenticatedAppAchatsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ventes/nouvelle': {
      id: '/_authenticated/app/ventes/nouvelle'
      path: '/ventes/nouvelle'
      fullPath: '/app/ventes/nouvelle'
      preLoaderRoute: typeof AuthenticatedAppVentesNouvelleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ventes/$id': {
      id: '/_authenticated/app/ventes/$id'
      path: '/ventes/$id'
      fullPath: '/app/ventes/$id'
      preLoaderRoute: typeof AuthenticatedAppVentesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tresorerie/$id': {
      id: '/_authenticated/app/tresorerie/$id'
      path: '/tresorerie/$id'
      fullPath: '/app/tresorerie/$id'
      preLoaderRoute: typeof AuthenticatedAppTresorerieIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comptabilite/plan': {
      id: '/_authenticated/app/comptabilite/plan'
      path: '/plan'
      fullPath: '/app/comptabilite/plan'
      preLoaderRoute: typeof AuthenticatedAppComptabilitePlanRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/periodes': {
      id: '/_authenticated/app/comptabilite/periodes'
      path: '/periodes'
      fullPath: '/app/comptabilite/periodes'
      preLoaderRoute: typeof AuthenticatedAppComptabilitePeriodesRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/journaux': {
      id: '/_authenticated/app/comptabilite/journaux'
      path: '/journaux'
      fullPath: '/app/comptabilite/journaux'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteJournauxRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/journal': {
      id: '/_authenticated/app/comptabilite/journal'
      path: '/journal'
      fullPath: '/app/comptabilite/journal'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteJournalRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/grand-livre': {
      id: '/_authenticated/app/comptabilite/grand-livre'
      path: '/grand-livre'
      fullPath: '/app/comptabilite/grand-livre'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteGrandLivreRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/balance-auxiliaire': {
      id: '/_authenticated/app/comptabilite/balance-auxiliaire'
      path: '/balance-auxiliaire'
      fullPath: '/app/comptabilite/balance-auxiliaire'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteBalanceAuxiliaireRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/balance': {
      id: '/_authenticated/app/comptabilite/balance'
      path: '/balance'
      fullPath: '/app/comptabilite/balance'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteBalanceRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/achats/nouvelle': {
      id: '/_authenticated/app/achats/nouvelle'
      path: '/achats/nouvelle'
      fullPath: '/app/achats/nouvelle'
      preLoaderRoute: typeof AuthenticatedAppAchatsNouvelleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/achats/$id': {
      id: '/_authenticated/app/achats/$id'
      path: '/achats/$id'
      fullPath: '/app/achats/$id'
      preLoaderRoute: typeof AuthenticatedAppAchatsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comptabilite/ecritures/': {
      id: '/_authenticated/app/comptabilite/ecritures/'
      path: '/ecritures'
      fullPath: '/app/comptabilite/ecritures/'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteEcrituresIndexRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/ecritures/nouvelle': {
      id: '/_authenticated/app/comptabilite/ecritures/nouvelle'
      path: '/ecritures/nouvelle'
      fullPath: '/app/comptabilite/ecritures/nouvelle'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteEcrituresNouvelleRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
    '/_authenticated/app/comptabilite/ecritures/$id': {
      id: '/_authenticated/app/comptabilite/ecritures/$id'
      path: '/ecritures/$id'
      fullPath: '/app/comptabilite/ecritures/$id'
      preLoaderRoute: typeof AuthenticatedAppComptabiliteEcrituresIdRouteImport
      parentRoute: typeof AuthenticatedAppComptabiliteRoute
    }
  }
}

interface AuthenticatedAppComptabiliteRouteChildren {
  AuthenticatedAppComptabiliteBalanceRoute: typeof AuthenticatedAppComptabiliteBalanceRoute
  AuthenticatedAppComptabiliteBalanceAuxiliaireRoute: typeof AuthenticatedAppComptabiliteBalanceAuxiliaireRoute
  AuthenticatedAppComptabiliteGrandLivreRoute: typeof AuthenticatedAppComptabiliteGrandLivreRoute
  AuthenticatedAppComptabiliteJournalRoute: typeof AuthenticatedAppComptabiliteJournalRoute
  AuthenticatedAppComptabiliteJournauxRoute: typeof AuthenticatedAppComptabiliteJournauxRoute
  AuthenticatedAppComptabilitePeriodesRoute: typeof AuthenticatedAppComptabilitePeriodesRoute
  AuthenticatedAppComptabilitePlanRoute: typeof AuthenticatedAppComptabilitePlanRoute
  AuthenticatedAppComptabiliteIndexRoute: typeof AuthenticatedAppComptabiliteIndexRoute
  AuthenticatedAppComptabiliteEcrituresIdRoute: typeof AuthenticatedAppComptabiliteEcrituresIdRoute
  AuthenticatedAppComptabiliteEcrituresNouvelleRoute: typeof AuthenticatedAppComptabiliteEcrituresNouvelleRoute
  AuthenticatedAppComptabiliteEcrituresIndexRoute: typeof AuthenticatedAppComptabiliteEcrituresIndexRoute
}

const AuthenticatedAppComptabiliteRouteChildren: AuthenticatedAppComptabiliteRouteChildren =
  {
    AuthenticatedAppComptabiliteBalanceRoute:
      AuthenticatedAppComptabiliteBalanceRoute,
    AuthenticatedAppComptabiliteBalanceAuxiliaireRoute:
      AuthenticatedAppComptabiliteBalanceAuxiliaireRoute,
    AuthenticatedAppComptabiliteGrandLivreRoute:
      AuthenticatedAppComptabiliteGrandLivreRoute,
    AuthenticatedAppComptabiliteJournalRoute:
      AuthenticatedAppComptabiliteJournalRoute,
    AuthenticatedAppComptabiliteJournauxRoute:
      AuthenticatedAppComptabiliteJournauxRoute,
    AuthenticatedAppComptabilitePeriodesRoute:
      AuthenticatedAppComptabilitePeriodesRoute,
    AuthenticatedAppComptabilitePlanRoute:
      AuthenticatedAppComptabilitePlanRoute,
    AuthenticatedAppComptabiliteIndexRoute:
      AuthenticatedAppComptabiliteIndexRoute,
    AuthenticatedAppComptabiliteEcrituresIdRoute:
      AuthenticatedAppComptabiliteEcrituresIdRoute,
    AuthenticatedAppComptabiliteEcrituresNouvelleRoute:
      AuthenticatedAppComptabiliteEcrituresNouvelleRoute,
    AuthenticatedAppComptabiliteEcrituresIndexRoute:
      AuthenticatedAppComptabiliteEcrituresIndexRoute,
  }

const AuthenticatedAppComptabiliteRouteWithChildren =
  AuthenticatedAppComptabiliteRoute._addFileChildren(
    AuthenticatedAppComptabiliteRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppComptabiliteRoute: typeof AuthenticatedAppComptabiliteRouteWithChildren
  AuthenticatedAppExportRoute: typeof AuthenticatedAppExportRoute
  AuthenticatedAppFiscaliteRoute: typeof AuthenticatedAppFiscaliteRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppTiersRoute: typeof AuthenticatedAppTiersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAchatsIdRoute: typeof AuthenticatedAppAchatsIdRoute
  AuthenticatedAppAchatsNouvelleRoute: typeof AuthenticatedAppAchatsNouvelleRoute
  AuthenticatedAppTresorerieIdRoute: typeof AuthenticatedAppTresorerieIdRoute
  AuthenticatedAppVentesIdRoute: typeof AuthenticatedAppVentesIdRoute
  AuthenticatedAppVentesNouvelleRoute: typeof AuthenticatedAppVentesNouvelleRoute
  AuthenticatedAppAchatsIndexRoute: typeof AuthenticatedAppAchatsIndexRoute
  AuthenticatedAppTresorerieIndexRoute: typeof AuthenticatedAppTresorerieIndexRoute
  AuthenticatedAppVentesIndexRoute: typeof AuthenticatedAppVentesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppComptabiliteRoute:
    AuthenticatedAppComptabiliteRouteWithChildren,
  AuthenticatedAppExportRoute: AuthenticatedAppExportRoute,
  AuthenticatedAppFiscaliteRoute: AuthenticatedAppFiscaliteRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppTiersRoute: AuthenticatedAppTiersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAchatsIdRoute: AuthenticatedAppAchatsIdRoute,
  AuthenticatedAppAchatsNouvelleRoute: AuthenticatedAppAchatsNouvelleRoute,
  AuthenticatedAppTresorerieIdRoute: AuthenticatedAppTresorerieIdRoute,
  AuthenticatedAppVentesIdRoute: AuthenticatedAppVentesIdRoute,
  AuthenticatedAppVentesNouvelleRoute: AuthenticatedAppVentesNouvelleRoute,
  AuthenticatedAppAchatsIndexRoute: AuthenticatedAppAchatsIndexRoute,
  AuthenticatedAppTresorerieIndexRoute: AuthenticatedAppTresorerieIndexRoute,
  AuthenticatedAppVentesIndexRoute: AuthenticatedAppVentesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CabinetsRoute: CabinetsRoute,
  ContactRoute: ContactRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
