revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.prevent_audit_mutation() from public, anon, authenticated;
revoke execute on function public.check_periode_ouverte() from public, anon, authenticated;
revoke execute on function public.check_abonnement_actif() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.attribuer_numero_ecriture(uuid, uuid, uuid) from public, anon, authenticated;
revoke execute on function public.attribuer_numero_achat(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.attribuer_numero_facture(uuid, uuid, facture_type) from public, anon, authenticated;
revoke execute on function public.seed_plan_ohada(uuid) from public, anon, authenticated;
revoke execute on function public.next_ecriture_numero(uuid, uuid, uuid) from public, anon, authenticated;
revoke execute on function public.activer_abonnement(uuid, subscription_status, timestamptz) from public, anon;
revoke execute on function public.validate_ecriture(uuid) from public, anon;
revoke execute on function public.contrepasser_ecriture(uuid, date) from public, anon;
revoke execute on function public.valider_achat(uuid) from public, anon;
revoke execute on function public.enregistrer_paiement_achat(uuid, numeric) from public, anon;
revoke execute on function public.valider_facture(uuid) from public, anon;
revoke execute on function public.enregistrer_reglement(uuid, numeric) from public, anon;
revoke execute on function public.create_entreprise_with_owner(text, text, regime_fiscal, text, date, date) from public, anon;
revoke execute on function public.generer_periodes(uuid) from public, anon;
revoke execute on function public.rouvrir_periode(uuid, text) from public, anon;
revoke execute on function public.verrouiller_periode(uuid) from public, anon;
revoke execute on function public.cloturer_periode(uuid) from public, anon;
revoke execute on function public.mettre_en_revue_periode(uuid) from public, anon;
revoke execute on function public.has_role(uuid, app_role) from public, anon;
revoke execute on function public.has_membership_role(uuid, uuid, membership_role[]) from public, anon;
revoke execute on function public.is_member_of(uuid, uuid) from public, anon;
revoke execute on function public.membership_role_of(uuid, uuid) from public, anon;